name: "ajmendez"
description: "Random bits of python and thoughts about visualization and astronomy from Alexander Mendez. "
author :
  name : Alexander Mendez
  email : blue.space@gmail.com
  github : ajmendez
  twitter : ajmendez

url: "https://ajmendez.github.io"
baseurl: ""
#markdown: redcarpet
highlighter: pygments
paginate: 5
paginate_path: "/blog/page:num/"

permalink: date
google: UA-22320868-3


# excerpt_separator: "<!-- more -->"
